[package]
name = "buildlens-tests"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
buildlens-core = { path = "../buildlens-core" }
buildlens-parser = { path = "../buildlens-parser" }
regex.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
