[package]
name = "buildlens-dashboard"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
buildlens-core = { path = "../buildlens-core" }
buildlens-storage = { path = "../buildlens-storage" }
serde_json.workspace = true
serde.workspace = true
tiny_http.workspace = true
anyhow.workspace = true
